/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 11:15:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.pragati.service.PassengerServiceImpl;
import com.pragati.service.PassengerService;
import com.pragati.model.Passenger;

public final class passenger_005fadd_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/passenger_list.jsp", Long.valueOf(1672312385952L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pragati.service.PassengerServiceImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pragati.service.PassengerService");
    _jspx_imports_classes.add("com.pragati.model.Passenger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Passenger</title>\r\n");
      out.write(" <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"passenger_add.jsp\" method=\"post\" class=\"container form\">\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"exampleFormControlInput1\" class=\"form-label\">User Name</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"name\" required=\"required\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label for=\"exampleFormControlInput1\" class=\"form-label\">Gender</label>\r\n");
      out.write("		  \r\n");
      out.write("			<div class=\"form-check\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"male\" >\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"flexRadioDefault1\" >Male</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-check\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"female\" checked>\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"flexRadioDefault2\">Female</label>\r\n");
      out.write("			</div>\r\n");
      out.write("		  \r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label>Select country :</label>\r\n");
      out.write("			<select name=\"country\" required=\"required\">\r\n");
      out.write("				<option value=\"India\" >India</option>\r\n");
      out.write("				<option value=\"USA\" >USA</option>\r\n");
      out.write("				<option value=\"UK\" >UK</option>\r\n");
      out.write("				<option value=\"Dubai\" >Dubai</option>\r\n");
      out.write("				<option value=\"Nepal\" >Nepal</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"exampleFormControlInput1\" class=\"form-label\" >About You</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"about\" required=\"required\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"form-check\">\r\n");
      out.write("			<input class=\"form-check-input\" type=\"checkbox\" name=\"maillist\" id=\"flexCheckDefault\" value=\"true\" > \r\n");
      out.write("				<label class=\"form-check-label\" for=\"flexCheckDefault\"> Would you like to join our mail list? </label>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div>\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-primary\">Add</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	PassengerService passengerService = new PassengerServiceImpl();
	List<Passenger> passengers = passengerService.getAll(0);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<table class=\"table\">\r\n");
      out.write("	  <thead>\r\n");
      out.write("	    <tr>\r\n");
      out.write("	      <th scope=\"col\">Name</th>\r\n");
      out.write("	      <th scope=\"col\">Gender</th>\r\n");
      out.write("	      <th scope=\"col\">Country</th>\r\n");
      out.write("	      <th scope=\"col\">About You</th>\r\n");
      out.write("	      <th scope=\"col\">Mailing List</th>\r\n");
      out.write("	      <th scope=\"col\"></th>\r\n");
      out.write("	      <th scope=\"col\"></th>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	  </thead>\r\n");
      out.write("	  <tbody>\r\n");
      out.write("	  ");
for (Passenger passenger : passengers){ 
      out.write("\r\n");
      out.write("	    <tr>\r\n");
      out.write("	      <td>");
      out.print(passenger.getName() );
      out.write("</td>\r\n");
      out.write("	      <td>");
      out.print(passenger.getGender() );
      out.write("</td>\r\n");
      out.write("	      <td>");
      out.print(passenger.getCountry() );
      out.write("</td>\r\n");
      out.write("	      <td>");
      out.print(passenger.getAbout() );
      out.write("</td>\r\n");
      out.write("	      <td>");
      out.print(passenger.getMaillist() );
      out.write("</td>\r\n");
      out.write("	      <td><a href=\"passenger_delete.jsp?id=");
      out.print(passenger.getId());
      out.write("\">Delete</a></td>\r\n");
      out.write("	      <td><a href=\"passenger_update.jsp?id=");
      out.print(passenger.getId());
      out.write("\">Update</a></td>\r\n");
      out.write("	    </tr>\r\n");
      out.write("	   ");
} 
      out.write("\r\n");
      out.write("	  </tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
