using Employee2;

/*Create a Class Employee with the following specifications

Properties
----------
string Name -> no blank names should be allowed
int EmpNo ->  must be readonly and autogenerated
decimal Basic -> must be between some range
short DeptNo -> must be > 0

Methods
-------
decimal GetNetSalary() -> returns calculated net salary (Use any formula to get net salary based on Basic salary)


Create constructors to accept initial values for Employee obj
Employee o1 = new Employee("Amol", 123465, 10);
Employee o2 = new Employee("Amol", 123465);
Employee o3 = new Employee("Amol");
Employee o4 = new Employee();

EmpNo must be autogenerated ... i.e.
first object should automatically get EmpNo 1
second object should automatically get EmpNo 2
third object should automatically get EmpNo 3
...and so on...

Test Cases
Employee o1 = new Employee()
Employee o2 = new Employee()
Employee o3 = new Employee()
cw(o1.EmpNo)
cw(o2.EmpNo)
cw(o3.EmpNo)

cw(o3.EmpNo)
cw(o2.EmpNo)
cw(o1.EmpNo)*/

namespace Employee2
{
    internal class Employee
    {
        private String name;
        private int empNo;
        private decimal basic;
        private short deptNo;
        private static int count = 0;

        public String NAME
        {
            get
            { return name; }
            set
            {
                if (value.Length != 0)
                    name = value;
                else
                    Console.WriteLine("Invalid Name");

            }
        }

        public int EMPNO
        {
            get { return empNo+=1; }
        }

        public decimal BASIC
        {
            get { return basic; }
            set
            {
                if (value > 10000 && value < 250000)
                {
                    basic = value;
                }
                else
                    Console.WriteLine("Invalid basic pay");
            }
        }
        public short DEPTNO
        {
            get { return deptNo; }
            set
            {
                if (value > 0)
                    deptNo = value;
                else
                    Console.WriteLine("Invalid deptNo");
            }
        }

        public Employee(String name = "Pragati", decimal basic = 12500.5m, short deptNO = 2)
        {
            count++;
            this.name = name;
            this.basic = basic;
            this.deptNo = deptNO;
            this.empNo= count;
        }
        public decimal GetNetSalary(decimal basic)
        {
            decimal netSal = (decimal)basic * 0.6m;
            return netSal;
        }

        public static void Display(Employee o)
        {
            Console.WriteLine(o.empNo + " " + o.name + " " + o.basic + " " + o.deptNo);
        }

        static void Main(string[] args)
        {
            Employee o1 = new Employee();
            Employee o2 = new Employee();
            Employee o3 = new Employee();
            Employee o4 = new Employee();   

            Console.WriteLine(o1.empNo);
            Console.WriteLine(o2.empNo);
            Console.WriteLine(o3.empNo);
            Console.WriteLine(o4.empNo);

            Console.WriteLine(o4.empNo);
            Console.WriteLine(o3.empNo);
            Console.WriteLine(o2.empNo);
            Console.WriteLine(o1.empNo);

        }
    }
}