/*Create the following classes
Employee
   Prop	
	string Name -> no blanks
	int EmpNo -> readonly, autogenerated
	short DeptNo -> > 0
	abstract decimal Basic 
   Methods
	abstract decimal CalcNetSalary()


Manager : Employee
   Prop
	string Designation -> cant be blank
	

GeneralManager : Manager
   Prop
 	string Perks -> no validations

CEO : Employee
      Make CalNetSalary() a sealed method
*/

using System.Runtime.ConstrainedExecution;
using System.Xml.Linq;

namespace EmployeeInterface3
{
    
    public class Demo
    {
        static void Main(string[] args)
        {
            Manager m = new("Pragati", 21, "Manager", 60000);

            GeneralManager gm = new("Pooja", 20, "General-Manager", 46000,"free travel");

            CEO ceo = new("Prachi", 1, 10000);

            m.Display();
            gm.Display();
            ceo.Display();

        }
    }
    
    

    

}
